-- Configuration
require("config/config")

-- Modules
require("shared/modules/formatters/types/formatters")
require("shared/modules/helpers/types/helpers")
require("shared/modules/teams/types/teams")

-- Derive from sandbox
DeriveGamemode("sandbox")

-- Set the gamemode information
GM.Name    = "SledBuild Remastered v1.0"
GM.Author  = "jotalanusse"
GM.Email   = "jotalanusse@gmail.com"
GM.Website = "jotalanusse.github.io"

-- Initialize
-- TODO: Implement
