global GM: GMType

global PrintTable: function(tableToPrint: any, indent: integer, done: table) -- TODO: Add types

global DeriveGamemode: function(_base : string)

global include: function(_fileName: string): any
global AddCSLuaFile: function(_fileName: string)

global COLLISION_GROUP_DEBRIS_TRIGGER: integer

global Color: function(_r: integer, _g: integer, _b: integer, _a: integer): ColorType
global Vector: function(_x: number, _y: number, _z: number): VectorType
