global GM: GMType

global PrintTable: function(tableToPrint: any, indent: integer, done: table) -- TYPE: Add type to tableToPrint?

global DeriveGamemode: function(base : string)

global include: function(fileName: string): any
global AddCSLuaFile: function(fileName: string)

global COLLISION_GROUP_DEBRIS_TRIGGER: integer

global Color: function(r: integer, g: integer, b: integer, a: integer): ColorType
global Vector: function(x: number, y: number, z: number): VectorType
