global enum PropModelEnum
  -- Props
  "models/props_phx/oildrum001_explosive.mdl"
  "models/props_junk/gascan001a.mdl"
  "models/props_junk/propane_tank001a.mdl"
  "models/props_c17/oildrum001_explosive.mdl"
  "models/props_phx/misc/flakshell_big.mdl"
  "models/props_phx/ww2bomb.mdl"
  "models/props_phx/amraam.mdl"
  "models/props_phx/mk-82.mdl"
  "models/props_phx/ball.mdl"
  "models/props_phx/cannonball.mdl"
  "models/props_phx/torpedo.mdl"

  -- Vehicles
  "models/vehicles/prisoner_pod_inner.mdl"
  "models/nova/airboat_seat.mdl"
end
